/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CakeShopKurlaRouteImport } from './routes/cake-shop-kurla'
import { Route as IndexRouteImport } from './routes/index'

const CakeShopKurlaRoute = CakeShopKurlaRouteImport.update({
  id: '/cake-shop-kurla',
  path: '/cake-shop-kurla',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cake-shop-kurla': typeof CakeShopKurlaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cake-shop-kurla': typeof CakeShopKurlaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cake-shop-kurla': typeof CakeShopKurlaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cake-shop-kurla'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cake-shop-kurla'
  id: '__root__' | '/' | '/cake-shop-kurla'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CakeShopKurlaRoute: typeof CakeShopKurlaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cake-shop-kurla': {
      id: '/cake-shop-kurla'
      path: '/cake-shop-kurla'
      fullPath: '/cake-shop-kurla'
      preLoaderRoute: typeof CakeShopKurlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CakeShopKurlaRoute: CakeShopKurlaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
